This notebook is for feature engineering required for processing the data used for modeling.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/processed.csv')
df.head()

,Unnamed: 0,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,...,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV
0,0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,...,39.65,0.00,20,0.00,59.65,3,Churned,Yes,91,5433
1,1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,...,633.30,0.00,0,390.80,1024.10,3,Churned,Yes,69,5302
2,2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,...,1752.55,45.61,0,203.94,1910.88,2,Churned,Yes,81,3179
3,3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,...,2514.50,13.43,0,494.00,2995.07,2,Churned,Yes,88,5337
4,4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,...,2868.15,0.00,0,234.21,3102.36,2,Churned,Yes,67,2793

In [3]:
tenure_bins = [0, 6, 12, 24, np.inf]
labels = ['0-6', '6-12', '12-24', '24+']

df['Tenure_Bucket'] = pd.cut(df['Tenure in Months'], bins=tenure_bins, labels=labels, right=False)
df[['Tenure in Months', 'Tenure_Bucket']].head(10)

   Tenure in Months Tenure_Bucket
0                 1           0-6
1                 8          6-12
2                18         12-24
3                25           24+
4                37           24+
5                27           24+
6                 1           0-6
7                58           24+
8                15         12-24
9                 7          6-12

In [4]:
df['Value_Segment'] = pd.qcut(df['CLTV'], q=3, labels=['Low', 'Medium', 'High'])

df[['CLTV', 'Value_Segment']].head(10)

   CLTV Value_Segment
0  5433          High
1  5302          High
2  3179           Low
3  5337          High
4  2793           Low
5  4638        Medium
6  3964           Low
7  5444          High
8  5717          High
9  4419        Medium

In [5]:
df['Revenue_per_Month'] = df['Total Revenue'] / df['Tenure in Months']

df['Revenue_per_Month'] = df['Revenue_per_Month'].replace([float('inf')], 0)
df['Revenue_per_Month'] = df['Revenue_per_Month'].fillna(0)

In [6]:
df['Revenue_Deviation'] = df['Revenue_per_Month'] / df['Monthly Charge']

df[['Total Revenue', 'CLTV', 'Monthly Charge', 'Revenue_per_Month', 'Revenue_Deviation']].head(10)

   Total Revenue  CLTV  Monthly Charge  Revenue_per_Month  Revenue_Deviation
0          59.65  5433           39.65          59.650000           1.504414
1        1024.10  5302           80.65         128.012500           1.587260
2        1910.88  3179           95.45         106.160000           1.112205
3        2995.07  5337           98.50         119.802800           1.216272
4        3102.36  2793           76.50          83.847568           1.096047
5        2235.41  4638           78.05          82.792963           1.060768
6          85.73  3964           70.45          85.730000           1.216891
7        2610.25  5444           45.30          45.004310           0.993473
8        1806.75  5717           74.45         120.450000           1.617864
9         681.20  4419           76.45          97.314286           1.272914

In [7]:
cols_to_drop = ['Under 30', 'Senior Citizen', 'Quarter', 'Country', 'State', 'City', 'Zip Code', 'Churn Reason', 'Churn Score', 'CLTV', 'Customer Status']
df = df.drop(columns=[col for col in cols_to_drop if col in df.columns])
df = df.drop(['Customer ID'], axis=1)

In [8]:
df.to_csv('../data/processed.csv')